In [1]:
import numpy as np

In [65]:
A = np.matrix([[3.,2.,4.],[1.,1.,2.],[4.,3.,2.]])
print(A)

[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3.  2.]]


In [66]:
# Determinante de A:

x = np.linalg.det(A)
print(x)

if x != 0:
    print('true')

-4.0
true


In [74]:
# Obtendo o multiplicador M0

M0 = np.zeros((3,3))

M0[1,0] = - A[1,0]/A[0,0]
M0[2,0] = - A[2,0]/A[0,0]

for i in range(3):
    M0[i,i] = 1

print(M0)

[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


In [75]:
# Multiplicando M0 por A para obter A1

A1 = M0*A

print(A1)

[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [76]:
# Obtendo o multiplicador M1

M1 = np.zeros((3,3))

M1[2,1] = - A1[2,1]/A1[1,1]

for i in range(3):
    M1[i,i] = 1
    
print(M1)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]


In [77]:
# Multiplicando M1 por A1 para obter A2

A2 = M1*A1

print(A2)

[[  3.00000000e+00   2.00000000e+00   4.00000000e+00]
 [  0.00000000e+00   3.33333333e-01   6.66666667e-01]
 [  0.00000000e+00   5.55111512e-17  -4.00000000e+00]]


In [81]:
# Preparando o B para utilização

b = np.matrix([[1],[2],[3]])

b1 = M0*b
b2 = M1*b1

print(b2)

[[  1.00000000e+00]
 [  1.66666667e+00]
 [ -4.44089210e-16]]
