In [1]:
import numpy as np

In [35]:
A = np.matrix([[3.,2.,4.],[1.,1.,2.],[4.,3.,2.]])
print(A)

[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3.  2.]]


In [36]:
# Determinante de A:

x = np.linalg.det(A)
print(x)

if x != 0:
    print('true')

-4.0
true


In [37]:
# Obtendo os multiplicadores M10 e M20

M = np.zeros((3,3))

M[1,0] = - A[1,0]/A[0,0]
M[2,0] = - A[2,0]/A[0,0]

for i in range(3):
    M[i,i] = 1

print(M)

[[ 1.          0.          0.        ]
 [-0.33333333  1.          0.        ]
 [-1.33333333  0.          1.        ]]


In [52]:
# Multiplicando M por A

A1 = M*A

print(A1)

[[ 3.          2.          4.        ]
 [ 0.          0.33333333  0.66666667]
 [ 0.          0.33333333 -3.33333333]]


In [51]:
# Obtendo o multiplicador M21

N = np.zeros((3,3))

N[2,1] = - P[2,1]/P[1,1]

for i in range(3):
    N[i,i] = 1
    
print(N)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0. -1.  1.]]


In [53]:
# Multiplicando N por A1

A2 = N*A1

print(A2)

[[  3.00000000e+00   2.00000000e+00   4.00000000e+00]
 [  0.00000000e+00   3.33333333e-01   6.66666667e-01]
 [  0.00000000e+00   5.55111512e-17  -4.00000000e+00]]
