In [1]:
import numpy as np

In [4]:
A = np.matrix([[3.,2.,4.],[1.,1.,2.],[4.,3.,2.]])
print(A)

[[ 3.  2.  4.]
 [ 1.  1.  2.]
 [ 4.  3.  2.]]


In [5]:
# Determinante de A
x = np.linalg.det(A)
print(x)

if x != 0:
    print('true')

-4.0
true
